DROP TABLE AREA;
DROP TABLE AREAPOINT;
DROP TABLE CHILDREN;
DROP TABLE FAMILY;
DROP TABLE MARKER;
DROP TABLE PARENT;
DROP TABLE PARENTSETTINGS;

DROP TRIGGER AREAPOINT_TRG;
DROP TRIGGER AREA_TRG;
DROP TRIGGER CHILDREN_TRG;
DROP TRIGGER FAMILY_TRG;
DROP TRIGGER MARKER_TRG;
DROP TRIGGER PARENT_TRG;
DROP TRIGGER PARENTSETTINGS_TRG;

DROP SEQUENCE AREA_SEQ;
DROP SEQUENCE AREAPOINT_SEQ;
DROP SEQUENCE CHILDREN_SEQ;
DROP SEQUENCE FAMILY_SEQ;
DROP SEQUENCE MARKER_SEQ;
DROP SEQUENCE PARENT_SEQ;
DROP SEQUENCE PARENTSETTINGS_SEQ;

CREATE SEQUENCE AREA_SEQ;
CREATE SEQUENCE AREAPOINT_SEQ;
CREATE SEQUENCE CHILDREN_SEQ;
CREATE SEQUENCE FAMILY_SEQ;
CREATE SEQUENCE MARKER_SEQ;
CREATE SEQUENCE PARENT_SEQ;
CREATE SEQUENCE PARENTSETTINGS_SEQ;

CREATE TABLE "STUDENT"."AREA"
  (
    "IDAREA"      NUMBER(19,0) NOT NULL ENABLE,
    "IDAREAPOINT" NUMBER(19,0) NOT NULL ENABLE,
    "IDCHILD"     NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "AREA_PK" PRIMARY KEY ("IDAREA") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."AREA_TRG" BEFORE
  INSERT ON AREA FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDAREA IS NULL THEN
  SELECT AREA_SEQ.NEXTVAL INTO :NEW.IDAREA FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."AREA_TRG" ENABLE;


CREATE TABLE "STUDENT"."AREAPOINT"
  (
    "IDAREAPOINT" NUMBER(19,0) NOT NULL ENABLE,
    "IDAREA"      NUMBER(19,0) NOT NULL ENABLE,
    "X" FLOAT(126) NOT NULL ENABLE,
    "Y" FLOAT(126) NOT NULL ENABLE,
    CONSTRAINT "AREAPOINT_PK" PRIMARY KEY ("IDAREAPOINT") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE,
    CONSTRAINT "AREAPOINT_AREA_FK1" FOREIGN KEY ("IDAREA") REFERENCES "STUDENT"."AREA" ("IDAREA") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."AREAPOINT_TRG" BEFORE
  INSERT ON AREAPOINT FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDAREAPOINT IS NULL THEN
  SELECT AREAPOINT_SEQ.NEXTVAL INTO :NEW.IDAREAPOINT FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."AREAPOINT_TRG" ENABLE;


CREATE TABLE "STUDENT"."CHILDREN"
  (
    "IDCHILD"   NUMBER(19,0) NOT NULL ENABLE,
    "IDAREA"    NUMBER(19,0) NOT NULL ENABLE,
    "CHILDNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "IMEI"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "KEY"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "DATEOFBIRTH" DATE,
    CONSTRAINT "I_PK" PRIMARY KEY ("IDCHILD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."I_TRG" BEFORE
  INSERT ON CHILDREN FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDCHILD IS NULL THEN
  SELECT I_SEQ.NEXTVAL INTO :NEW.IDCHILD FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."I_TRG" ENABLE;


CREATE TABLE "STUDENT"."FAMILY"
  (
    "IDFAMILY" NUMBER(19,0) NOT NULL ENABLE,
    "IDPARENT" NUMBER(19,0) NOT NULL ENABLE,
    "IDCHILD"  NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "FAMILY_PK" PRIMARY KEY ("IDFAMILY") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."FAMILY_TRG" BEFORE
  INSERT ON FAMILY FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDFAMILY IS NULL THEN
  SELECT FAMILY_SEQ.NEXTVAL INTO :NEW.IDFAMILY FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."FAMILY_TRG" ENABLE;


CREATE TABLE "STUDENT"."MARKER"
  (
    "IDMARKER" NUMBER NOT NULL ENABLE,
    "IDCHILD"  NUMBER NOT NULL ENABLE,
    "X"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "Y"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "DATETIME" DATE NOT NULL ENABLE,
    CONSTRAINT "MARKER_PK" PRIMARY KEY ("IDMARKER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."MARKER_TRG" BEFORE
  INSERT ON MARKER FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDMARKER IS NULL THEN
  SELECT MARKER_SEQ.NEXTVAL INTO :NEW.IDMARKER FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."MARKER_TRG" ENABLE;


CREATE TABLE "STUDENT"."PARENT"
  (
    "IDPARENT"        NUMBER(19,0) NOT NULL ENABLE,
    "SHORTEDPASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "EMAIL"           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "PARENTNAME"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PARENT_PK" PRIMARY KEY ("IDPARENT") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."PARENT_TRG" BEFORE
  INSERT ON PARENT FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDPARENT IS NULL THEN
  SELECT PARENT_SEQ.NEXTVAL INTO :NEW.IDPARENT FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."PARENT_TRG" ENABLE;


CREATE TABLE "STUDENT"."PARENTSETTINGS"
  (
    "IDPARENTSETTINGS" NUMBER(19,0) NOT NULL ENABLE,
    "IDPARENT"         NUMBER(19,0) NOT NULL ENABLE,
    "IDCHILD"          NUMBER(19,0) NOT NULL ENABLE,
    "STEPTIME" FLOAT(126) NOT NULL ENABLE,
    CONSTRAINT "PARENTSETTINGS_PK" PRIMARY KEY ("IDPARENTSETTINGS") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE OR REPLACE TRIGGER "STUDENT"."PARENTSETTINGS_TRG" BEFORE
  INSERT ON PARENTSETTINGS FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.IDPARENTSETTINGS IS NULL THEN
  SELECT PARENTSETTINGS_SEQ.NEXTVAL INTO :NEW.IDPARENTSETTINGS FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "STUDENT"."PARENTSETTINGS_TRG" ENABLE;
